events {
    worker_connections 1024;
}
pid logs/sitio2.pid;

http {
    server {
        listen 82;

        location / {
            root /mnt/c/Users/Stephanie/desarrolloweb/tmp/17289/nginx/3sitios/sitio2;
            index index.html;
        }
    }
}