events {
    worker_connections 1024;
}
pid logs/sitio1.pid;

http {
    server {
        listen 81;

        location / {
            root /mnt/c/Users/Stephanie/desarrolloweb/tmp/17289/nginx/3sitios/sitio1;
            index index.html;
        }
    }
}